# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\"9\n\x11\x46ileUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"5\n\x12\x46ileUploadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x13\x46ileDownloadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\")\n\x14\x46ileDownloadResponse\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\"&\n\x11\x46ileDeleteRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"5\n\x12\x46ileDeleteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10ListFilesRequest\"\'\n\x11ListFilesResponse\x12\x12\n\nfile_names\x18\x01 \x03(\t2\xee\x01\n\rMasterService\x12\x35\n\nUploadFile\x12\x12.FileUploadRequest\x1a\x13.FileUploadResponse\x12;\n\x0c\x44ownloadFile\x12\x14.FileDownloadRequest\x1a\x15.FileDownloadResponse\x12\x35\n\nDeleteFile\x12\x12.FileDeleteRequest\x1a\x13.FileDeleteResponse\x12\x32\n\tListFiles\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=16
  _globals['_FILEUPLOADREQUEST']._serialized_end=73
  _globals['_FILEUPLOADRESPONSE']._serialized_start=75
  _globals['_FILEUPLOADRESPONSE']._serialized_end=128
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=130
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=170
  _globals['_FILEDOWNLOADRESPONSE']._serialized_start=172
  _globals['_FILEDOWNLOADRESPONSE']._serialized_end=213
  _globals['_FILEDELETEREQUEST']._serialized_start=215
  _globals['_FILEDELETEREQUEST']._serialized_end=253
  _globals['_FILEDELETERESPONSE']._serialized_start=255
  _globals['_FILEDELETERESPONSE']._serialized_end=308
  _globals['_LISTFILESREQUEST']._serialized_start=310
  _globals['_LISTFILESREQUEST']._serialized_end=328
  _globals['_LISTFILESRESPONSE']._serialized_start=330
  _globals['_LISTFILESRESPONSE']._serialized_end=369
  _globals['_MASTERSERVICE']._serialized_start=372
  _globals['_MASTERSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
