# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\"8\n\x10\x46ileStoreRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"#\n\x11\x46ileStoreResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"(\n\x13\x46ileRetrieveRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\")\n\x14\x46ileRetrieveResponse\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\"&\n\x11\x46ileRemoveRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"$\n\x12\x46ileRemoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb7\x01\n\rWorkerService\x12\x32\n\tStoreFile\x12\x11.FileStoreRequest\x1a\x12.FileStoreResponse\x12;\n\x0cRetrieveFile\x12\x14.FileRetrieveRequest\x1a\x15.FileRetrieveResponse\x12\x35\n\nRemoveFile\x12\x12.FileRemoveRequest\x1a\x13.FileRemoveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILESTOREREQUEST']._serialized_start=16
  _globals['_FILESTOREREQUEST']._serialized_end=72
  _globals['_FILESTORERESPONSE']._serialized_start=74
  _globals['_FILESTORERESPONSE']._serialized_end=109
  _globals['_FILERETRIEVEREQUEST']._serialized_start=111
  _globals['_FILERETRIEVEREQUEST']._serialized_end=151
  _globals['_FILERETRIEVERESPONSE']._serialized_start=153
  _globals['_FILERETRIEVERESPONSE']._serialized_end=194
  _globals['_FILEREMOVEREQUEST']._serialized_start=196
  _globals['_FILEREMOVEREQUEST']._serialized_end=234
  _globals['_FILEREMOVERESPONSE']._serialized_start=236
  _globals['_FILEREMOVERESPONSE']._serialized_end=272
  _globals['_WORKERSERVICE']._serialized_start=275
  _globals['_WORKERSERVICE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
